### ISSUE TITLE
Класс конфигурации - должен оканчиваться на ...Configuration или Config или Conf

### ISSUE THREAD

**Issue by dddpaul** [saymynamej/SpringBoot-It-Budget#10]
https://github.com/saymynamej/SpringBoot-It-Budget/blob/1db601eedad4b5644948382ff9747d6f99127a6a/lime/src/main/java/smn/service/com/email/JavaMainSender.java#L11

По имени класса я ожидаю, что он реализует Sender,  а это оказывается конфигурация, где создается бин SenderImpl. Запутано.

**Comment by saymynamej** [comment]
Исправил
