### ISSUE TITLE
Никаких сеттеров - fluent api в Lombok или билдер в Lombok

### ISSUE THREAD

**Issue by dddpaul** [saymynamej/SpringBoot-It-Budget#11]
https://github.com/saymynamej/SpringBoot-It-Budget/blob/1db601eedad4b5644948382ff9747d6f99127a6a/lime/src/main/java/smn/service/com/email/JavaMainSender.java#L24

**Comment by saymynamej** [comment]
Здесь немного не понял, разве я могу как-то внедрить аннотации ломбока в чужие классы? Ведь если бы мог, то смог бы нарушить инкапсуляцию.
