### ISSUE TITLE
Из конструктора непонятно что куда идет - нужен билдер

### ISSUE THREAD

**Issue by dddpaul** [saymynamej/SpringBoot-It-Budget#12]
https://github.com/saymynamej/SpringBoot-It-Budget/blob/1db601eedad4b5644948382ff9747d6f99127a6a/lime/src/main/java/smn/service/com/security/memory/AlfaInMemoryUserDetailsManager.java#L32

**Comment by saymynamej** [comment]
заменил на билдер
