### ISSUE TITLE
Есть поговорка - когда программист пишет "else", умирает один котенок

### ISSUE THREAD

**Issue by dddpaul** [saymynamej/SpringBoot-It-Budget#13]
https://github.com/saymynamej/SpringBoot-It-Budget/blob/1db601eedad4b5644948382ff9747d6f99127a6a/lime/src/main/java/smn/service/com/security/memory/AlfaInMemoryUserDetailsManager.java#L40

Это антипаттерн, только запутывает. Пиши прямо - если юзер = нулл, то кидаем эксепшн. Потом ниже уже без всяких else. Еще это fail-fast называется.

**Comment by dddpaul** [comment]
Еще тут Optional можно

**Comment by dddpaul** [comment]
Ну и вообще, че-то стремновато выглядит. Если это что-то типа кэша, то нейминг я бы поменял: addUser и findUser.

В продакшен коде обычно уже готовые кэши используют, которые хорошо с БД интегрируются, там код писать почти не надо :)

В твоем случае ок, свой кэш на коленке, но подумай еще о многопоточности. У тебя бин один, методы не защищены synchrozide, HashMap потоконебезопасен. Можешь в одном потоке добавить юзера, а в другом получить null.

**Comment by saymynamej** [comment]
По if else - учел. К optional обязательно приучу себя.Поменял реализацию hashMap на concurrentHashMap.
