### ISSUE TITLE
Более элегантно инжектить через филды, а еще более красиво и совсем правильно - через конструктор + lombok

### ISSUE THREAD

**Issue by dddpaul** [saymynamej/SpringBoot-It-Budget#4]
https://github.com/saymynamej/SpringBoot-It-Budget/blob/1db601eedad4b5644948382ff9747d6f99127a6a/lime/src/main/java/smn/service/com/controller/DataController.java#L36

**Comment by saymynamej** [comment]
На сколько я знаю, spring не рекомендует делать инжект через понял, а вот конструктор+ломбок полностью согласен.

**Comment by saymynamej** [comment]
> На сколько я знаю, spring не рекомендует делать инжект через поля, а вот конструктор+ломбок полностью согласен. Но иногда когда есть циклическая завимость без сетера не обойтись.
