### ISSUE TITLE
Code smells - очень много всего в контроллере, надо разбивать

### ISSUE THREAD

**Issue by dddpaul** [saymynamej/SpringBoot-It-Budget#5]
https://github.com/saymynamej/SpringBoot-It-Budget/blob/1db601eedad4b5644948382ff9747d6f99127a6a/lime/src/main/java/smn/service/com/controller/PageController.java#L33

Плюс завязки на строковые поля в модели - а если они изменятся?

**Comment by saymynamej** [comment]
Убрал не нужный метод в контролере, остался один, который формирует главную страницу. По поводу завязок на поля - понял.

**Comment by saymynamej** [comment]
Убрал не нужный метод в контролере, остался один, который формирует главную страницу. По поводу завязок на поля - понял, в данный момент не могу изменить на метод addAttribute(Object o) так как еще надо будет перекопать фронт, как только время появится обязательно переделаю, так и в правду будет правильнее, и на будущее взял на заметку .
