### ISSUE TITLE
Кажется, здесь можно подумать о Enum

### ISSUE THREAD

**Issue by dddpaul** [saymynamej/SpringBoot-It-Budget#8]
https://github.com/saymynamej/SpringBoot-It-Budget/blob/1db601eedad4b5644948382ff9747d6f99127a6a/lime/src/main/java/smn/service/com/daoandservices/articleconstructor/ArticleConstructorServiceImpl.java#L112

**Comment by saymynamej** [comment]
+

**Comment by saymynamej** [comment]
> Согласен
