### ISSUE TITLE
Dao & Services - какой-то трэш

### ISSUE THREAD

**Issue by dddpaul** [saymynamej/SpringBoot-It-Budget#9]
https://github.com/saymynamej/SpringBoot-It-Budget/blob/1db601eedad4b5644948382ff9747d6f99127a6a/lime/src/main/java/smn/service/com/daoandservices/articleconstructor/ArticleConstructorServiceImpl.java#L166

Обычно их не смешивают, в сервисах - логика,  в Dao - только доступ к данным.
Ну и вообще, сейчас лучше юзать Spring Data, и переопределять только те методы, в которых ты хочешь сделать какие-то нетривиальные запросы.

**Comment by saymynamej** [comment]
Да, в данный момент во всех новых проектах я как раз использую spring data. По поводу логики полностью согласен, и всегда знал , что надо четко разделять доступ к данным и бизнес логику, сейчас посмотрел на код очень удивился почему я именно так сделал...
